(function() {var implementors = {};
implementors["tk_http"] = ["impl&lt;S:&nbsp;<a class='trait' href='https://docs.rs/tokio-core/0.1/tokio_core/io/trait.Io.html' title='tokio_core::io::Io'>Io</a>, D:&nbsp;<a class='trait' href='tk_http/server/trait.Dispatcher.html' title='tk_http::server::Dispatcher'>Dispatcher</a>&lt;S&gt;&gt; <a class='trait' href='https://docs.rs/futures/0.1/futures/future/trait.Future.html' title='futures::future::Future'>Future</a> for <a class='struct' href='tk_http/server/struct.Proto.html' title='tk_http::server::Proto'>Proto</a>&lt;S, D&gt;","impl&lt;S:&nbsp;<a class='trait' href='https://docs.rs/tokio-core/0.1/tokio_core/io/trait.Io.html' title='tokio_core::io::Io'>Io</a>&gt; <a class='trait' href='https://docs.rs/futures/0.1/futures/future/trait.Future.html' title='futures::future::Future'>Future</a> for <a class='struct' href='tk_http/server/struct.FutureRawBody.html' title='tk_http::server::FutureRawBody'>FutureRawBody</a>&lt;S&gt;","impl&lt;S:&nbsp;<a class='trait' href='https://docs.rs/tokio-core/0.1/tokio_core/io/trait.Io.html' title='tokio_core::io::Io'>Io</a>, T, D, E&gt; <a class='trait' href='https://docs.rs/futures/0.1/futures/future/trait.Future.html' title='futures::future::Future'>Future</a> for <a class='struct' href='tk_http/websocket/struct.Loop.html' title='tk_http::websocket::Loop'>Loop</a>&lt;S, T, D&gt; <span class='where'>where T: <a class='trait' href='https://docs.rs/futures/0.1/futures/stream/trait.Stream.html' title='futures::stream::Stream'>Stream</a>&lt;Item=<a class='enum' href='tk_http/websocket/enum.Packet.html' title='tk_http::websocket::Packet'>Packet</a>, Error=E&gt;, D: <a class='trait' href='tk_http/websocket/trait.Dispatcher.html' title='tk_http::websocket::Dispatcher'>Dispatcher</a>, E: <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html' title='core::fmt::Display'>Display</a></span>","impl&lt;S:&nbsp;<a class='trait' href='https://docs.rs/tokio-core/0.1/tokio_core/io/trait.Io.html' title='tokio_core::io::Io'>Io</a>, A&gt; <a class='trait' href='https://docs.rs/futures/0.1/futures/future/trait.Future.html' title='futures::future::Future'>Future</a> for <a class='struct' href='tk_http/websocket/client/struct.HandshakeProto.html' title='tk_http::websocket::client::HandshakeProto'>HandshakeProto</a>&lt;S, A&gt; <span class='where'>where A: <a class='trait' href='tk_http/websocket/client/trait.Authorizer.html' title='tk_http::websocket::client::Authorizer'>Authorizer</a>&lt;S&gt;</span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
